version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565" # minecraft
    restart: always
    environment:
      TYPE: "FABRIC"
      PACKWIZ_URL: "https://modpacks.ryleu.me/cottagepack/packwiz/pack.toml"
      EULA: true
      MOTD: "CottageServer"
      DIFFICULTY: "NORMAL"
      SEED: "4671615705230958608"
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 8
      SIMULATION_DISTANCE: 5
      ENABLE_WHITELIST: false
      MEMORY: "4G"
      USE_AIKAR_FLAGS: true
      VERSION: "1.19.2"
    volumes:
      - ./data:/data
