name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e830fe7a7850f79f7ea6b77cc8040318c9d6a5b5da8f254b86fa7efe2fa24f1"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
