name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac16eb7211986df6f44183d00161e3d86cd858ef1260ba3d24fe79b1669576e7"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
