name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61ca045b14a980ad6b04923ba0a68a3689507728cf59d20c432c5671138ee971"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
