name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b43f62a8651bf5d38cfea8082e8abc6f17a1c1be24e02965e25afd18952575a7"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
