name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0e97af57f47950ecc773ac6c09c51b47417cdfae5aab01bf3d5aac740c27686"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
