name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f27048128ea6821c6eddfa0d151e0fb13190c99c7b2e2a03a413ded59bca7b6"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
