name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31e2de6af5a5728b31c8c9797138d8ebab6d3bcbdee5aa4075865635b08068b1"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
