name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a419b688787b4f6bd0b05b6c2e8dd965f98aeec2439a46dd0a9ad92c140a83c"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
