name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "989ae556bcdf11d71da565c26d4fa60c970588ca2ea0bd4a70054bc6e01cec7a"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
