name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc353d7c97724e9b67df194f6992c4dd3d8187f87504877228f3b5f18ef125a0"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
