name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dc7043644653118b8b32f0b932fe42535cad52fabc7f826c1bd511d7f3d680e"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
