name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19b14da3830c7e69c79007bdd50bf74cc93f7a999d3d3d8839a9cb0c7cf4f813"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
