name = "CottagePack"
author = "ryleu, otulpp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4320f15309b64399da57967fb4fa6c7ff8f1388a454770b8016119ef4d7c1d53"

[versions]
fabric = "0.15.7"
minecraft = "1.19.2"
